baseURL = "http://locahost:1313/docs"
publishDir = "public/docs"
disableKinds = "home"

languageCode = "en-us"
title = "Zamenhof docs"
theme = "minimal-bootstrap-hugo-theme"

pygmentsUseClasses = true

[permalinks]
#  page = "/:sections/:filename/"
#  docs = "/:sections/:filename/"

[params]
  logo = "img/excedo-zamenhof.svg"
  git_repo = "https://gitlab.com/zamenhof/zamenhof-doc/tree/master/content"
  slack_link = "https://slack.com/linktoinvite"
  description = "Zamenhof.net docs"
  includeBootstrapJs = true
  iphone_sizes = [ "120x120", "152x152", "180x180" ]
  favicon_sizes = [ "32x32", "128x128", "192x192" ]
