baseURL = "/"
languageCode = "en-us"
title = "Zamenhof docs"
theme = "minimal-bootstrap-hugo-theme"

[permalinks]
#  page = "/:sections/:filename/"
#  docs = "/:sections/:filename/"

[params]
  description = "Zamenhof.net docs"
  includeBootstrapJs = true
  iphone_sizes = [ "120x120", "152x152", "180x180" ]
  favicon_sizes = [ "32x32", "128x128", "192x192" ]
